edited the distributors schema to account for tokens
sendchinatownlove/ruby pull request #293
Opened 2020-11-16 22:30 UTC by ryannamgung

2020-11-16 22:32 UTC, justintmckibben requested changes

2020-11-16 22:32 UTC, justintmckibben commented on Gemfile.lock
> +    zeitwerk (2.4.1)
What is all of this? Might wanna revert this to master

2020-11-16 22:32 UTC, justintmckibben commented on db/migrate/20201116222055_add_tokens_to_distributors.rb
> +    add_column :distributors, :gift_card_login_state, :string, default: 'new', null: false
We should make this enum a number vs a string

2020-11-16 22:32 UTC, justintmckibben commented on db/migrate/20201116222055_add_tokens_to_distributors.rb
> +    add_column :distributors, :gift_card_login_state, :string, default: 'new', null: false
Also add the states in the model file

2021-05-17 23:00 UTC, jacoblb64 commented
Closing this as it's been way out of date

2021-05-17 23:00 UTC, closed without merging