removed is_distribution and updated campaign_id fields
sendchinatownlove/ruby pull request #307
Opened 2020-12-11 04:27 UTC by billy-yuan

I removed the `is_distribution` field and updated the `campaign_id` fields.

Would like a review to make sure my changes below align with the current business logic.

Lines refer to my diff:
- Line 111: If a campaign but a project doesnt exist, then process as a regular gam
- Lines 157-158: If a project exists, then square location id will be equal to the location id of the project

Once these changes are good to go, the front end mega gam checkout should be ready to be pushed as well since I've tested a mega gam payment and see my test transactions show up in the payment_intents table with a project ID and campaign ID. More than happy to do more testing though.

2020-12-11 04:46 UTC, justintmckibben requested changes
I think some tests need to be updated too!

2020-12-11 04:46 UTC, justintmckibben commented on app/controllers/charges_controller.rb
> +                    Campaign.find_by(id: charge_params[:campaign_id])
This can be `Campaign.find(charge_params[:campaign_id])`

2020-12-11 04:46 UTC, justintmckibben commented on app/controllers/charges_controller.rb
> +      @campaign = if charge_params[:campaign_id].present? && !project_id.present?
I think we can replace this whole line with:
`@campaign = Campaign.find_by(id: charge_params[:campaign_id]) if charge_params[:campaign_id].present?`

2020-12-19 16:34 UTC, stzhng commented
as suggested by previous standup this pr is blocked because the secrets or environment variable of location id is not defined. 

1) you can set it on your fork of the repo in github/secrets and assign random numbers
2) straight forwardsolution is closing this PR and adding sendchinatownlove/ruby as an upstream master and pushing to a branch. @billy-yuan 


![image](https://user-images.githubusercontent.com/3683993/102694280-fcd7fc80-41ed-11eb-92d2-19b71c13b2a7.png)

2020-12-25 15:23 UTC, closed without merging